version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    env_file: .env
    environment:
      - PORT=10000
      - NODE_ENV=production
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

  db:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mvp_database_g0ic
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://153.126.130.7:10000
    restart: always
    depends_on:
      - api

  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://153.126.130.7:10000
    restart: always
    depends_on:
      - api

volumes:
  db_data:
    driver: local
